// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrctohbfxxuqnmzmvdgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yY3RvaGJmeHh1cW5tem12ZGdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMjA0NDIsImV4cCI6MjA2MzU5NjQ0Mn0.TclFTANnmEhpGQL8KgDRBh3XdgkgCou86qIblOcOZVk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);